# -*- coding: utf-8 -*-
"""Exp5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PBoOj6AV4bkL8b62H_oJS5FfHnLw2VWb
"""

!pip install SpeechRecognition
import speech_recognition as sr

audio_file = 'harvard.wav'

target_words = ["that", "and"]

def recognize_speech(audio_file):
    # Create a recognizer object
    recognizer = sr.Recognizer()

    # Load the audio file
    try:
        with sr.AudioFile(audio_file) as source:
            audio = recognizer.record(source)

        # Recognize the speech in the audio file
        text = recognizer.recognize_google(audio)
        print(f"Recognized text: {text}")
        return text

    except:
      print("Some error occured")
      return None

def check_words_in_audio(file_path, target_words):
    """
    Check for the presence of target words in the speech recognized from an audio file.

    Parameters:
        file_path (str): Path to the audio file.
        target_words (list): List of words to check for in the audio transcription.
    """
    text = recognize_speech(file_path)
    if text is not None:
        # Check if target words are in the recognized text
        found_words = [word for word in target_words if word.lower() in text.lower()]
        if found_words:
            print("Found words:", found_words)
        else:
            print("No target words found in the audio.")
    else:
        print("No text recognized from the audio.")

# Call the function to check for target words in the audio file
check_words_in_audio(audio_file, target_words)