# -*- coding: utf-8 -*-
"""Exp7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PMDFfN2LX7ObRpI0vmlds588hNZoSPd7
"""

import numpy as np
import pandas as pd
from statsmodels.tsa.arima.model import ARIMA
np.random.seed(123)
data= np.random.randn(100)
# Convert the numpy array to a pandas dataframe
df = pd.DataFrame(data, columns=['Value'])
# Fit an ARIMA model to the data
model = ARIMA (df, order=(3,1,1))
# order of components = (AR, I, MA)
results = model.fit()
print(results.summary())