# -*- coding: utf-8 -*-
"""Exp8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15_3wU9pcmTCUUFYlVLKWaOa8zDO6ExJQ
"""

import librosa
import librosa.display
import matplotlib.pyplot as plt

# Load audio file
audio, sr = librosa.load('harvard.wav')

# Compute MFCC features
mfcc = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=3)

# Display MFCC features
plt.figure(figsize=(10, 4))
librosa.display.specshow(mfcc, sr=sr, x_axis='time', cmap='viridis')
plt.colorbar(format='%+2.0f dB')
plt.title('MFCC')
plt.tight_layout()
plt.show()